/////////////////////////////////////////////////////////////////////////////
// Name:        wxAboutBoxTestMainFrame.cpp
// Purpose:     
// Author:      Volodymir (T-Rex) Tryapichko
// Modified by: 
// Created:     24/01/2009 15:45:30
// RCS-ID:      
// Copyright:   Copyright (c) Volodymir (T-Rex) Tryapichko, 2009
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 24/01/2009 15:45:30

// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"

#ifdef __BORLANDC__
#pragma hdrstop
#endif

#ifndef WX_PRECOMP
#include "wx/wx.h"
#endif

////@begin includes
////@end includes

#include "wxAboutBoxTestMainFrame.h"
#include "wxMozillaLikeAboutBoxDialog.h"
#include <wx/aboutdlg.h>

////@begin XPM images
////@end XPM images
#include "header_png.h"

/*!
 * wxAboutBoxTestMainFrame type definition
 */

IMPLEMENT_CLASS( wxAboutBoxTestMainFrame, wxFrame )


/*!
 * wxAboutBoxTestMainFrame event table definition
 */

BEGIN_EVENT_TABLE( wxAboutBoxTestMainFrame, wxFrame )

////@begin wxAboutBoxTestMainFrame event table entries
    EVT_MENU( wxID_EXIT, wxAboutBoxTestMainFrame::OnEXITClick )

    EVT_MENU( ID_MOZILLA_LIKE_ABOUTBOX, wxAboutBoxTestMainFrame::OnMOZILLALIKEABOUTBOXClick )

    EVT_MENU( wxID_ABOUT, wxAboutBoxTestMainFrame::OnABOUTClick )

////@end wxAboutBoxTestMainFrame event table entries

END_EVENT_TABLE()


/*!
 * wxAboutBoxTestMainFrame constructors
 */

wxAboutBoxTestMainFrame::wxAboutBoxTestMainFrame()
{
    Init();
}

wxAboutBoxTestMainFrame::wxAboutBoxTestMainFrame( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
    Init();
    Create( parent, id, caption, pos, size, style );
}


/*!
 * wxAboutBoxTestMainFrame creator
 */

bool wxAboutBoxTestMainFrame::Create( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
////@begin wxAboutBoxTestMainFrame creation
    wxFrame::Create( parent, id, caption, pos, size, style );

    this->SetName(_T("ID_WXABOUTBOXTESTMAINFRAME"));
    CreateControls();
    Centre();
////@end wxAboutBoxTestMainFrame creation
    return true;
}


/*!
 * wxAboutBoxTestMainFrame destructor
 */

wxAboutBoxTestMainFrame::~wxAboutBoxTestMainFrame()
{
////@begin wxAboutBoxTestMainFrame destruction
////@end wxAboutBoxTestMainFrame destruction
}


/*!
 * Member initialisation
 */

void wxAboutBoxTestMainFrame::Init()
{
////@begin wxAboutBoxTestMainFrame member initialisation
////@end wxAboutBoxTestMainFrame member initialisation
}


/*!
 * Control creation for wxAboutBoxTestMainFrame
 */

void wxAboutBoxTestMainFrame::CreateControls()
{    
////@begin wxAboutBoxTestMainFrame content construction
    // Generated by DialogBlocks, 24/01/2009 16:46:15 (unregistered)

    wxAboutBoxTestMainFrame* itemFrame1 = this;

    wxMenuBar* menuBar = new wxMenuBar;
    wxMenu* itemMenu8 = new wxMenu;
    itemMenu8->Append(wxID_EXIT, _("Exit\tAlt+F4"), _T(""), wxITEM_NORMAL);
    menuBar->Append(itemMenu8, _("File"));
    wxMenu* itemMenu10 = new wxMenu;
    itemMenu10->Append(ID_MOZILLA_LIKE_ABOUTBOX, _("Mozilla-like about box"), _T(""), wxITEM_NORMAL);
    itemMenu10->AppendSeparator();
    itemMenu10->Append(wxID_ABOUT, _("About..."), _T(""), wxITEM_NORMAL);
    menuBar->Append(itemMenu10, _("Help"));
    itemFrame1->SetMenuBar(menuBar);

    wxBoxSizer* itemBoxSizer2 = new wxBoxSizer(wxVERTICAL);
    itemFrame1->SetSizer(itemBoxSizer2);

    wxPanel* itemPanel3 = new wxPanel( itemFrame1, ID_PANEL, wxDefaultPosition, wxDefaultSize, wxNO_BORDER|wxTAB_TRAVERSAL );
    itemPanel3->SetName(_T("ID_PANEL"));
    itemBoxSizer2->Add(itemPanel3, 1, wxGROW, 0);

    wxBoxSizer* itemBoxSizer4 = new wxBoxSizer(wxHORIZONTAL);
    itemPanel3->SetSizer(itemBoxSizer4);

    wxStaticText* itemStaticText5 = new wxStaticText( itemPanel3, wxID_STATIC, _("http://wxwidgets.info"), wxDefaultPosition, wxDefaultSize, wxALIGN_CENTRE );
    itemStaticText5->SetName(_T("wxID_STATIC"));
    itemStaticText5->SetFont(wxFont(28, wxSWISS, wxNORMAL, wxNORMAL, false, wxT("")));
    itemBoxSizer4->Add(itemStaticText5, 1, wxALIGN_CENTER_VERTICAL, 5);

    wxStatusBar* itemStatusBar6 = new wxStatusBar( itemFrame1, ID_STATUSBAR, wxST_SIZEGRIP|wxNO_BORDER );
    itemStatusBar6->SetName(_T("ID_STATUSBAR"));
    itemStatusBar6->SetFieldsCount(2);
    itemFrame1->SetStatusBar(itemStatusBar6);

////@end wxAboutBoxTestMainFrame content construction
#if defined(__WXMSW__)
	SetIcon(wxICON(wxICON_AAA));
#endif
}


/*!
 * Should we show tooltips?
 */

bool wxAboutBoxTestMainFrame::ShowToolTips()
{
    return true;
}

/*!
 * Get bitmap resources
 */

wxBitmap wxAboutBoxTestMainFrame::GetBitmapResource( const wxString& name )
{
    // Bitmap retrieval
////@begin wxAboutBoxTestMainFrame bitmap retrieval
    wxUnusedVar(name);
    return wxNullBitmap;
////@end wxAboutBoxTestMainFrame bitmap retrieval
}

/*!
 * Get icon resources
 */

wxIcon wxAboutBoxTestMainFrame::GetIconResource( const wxString& name )
{
    // Icon retrieval
////@begin wxAboutBoxTestMainFrame icon retrieval
    wxUnusedVar(name);
    return wxNullIcon;
////@end wxAboutBoxTestMainFrame icon retrieval
}


/*!
 * wxEVT_COMMAND_MENU_SELECTED event handler for ID_MENU
 */

void wxAboutBoxTestMainFrame::OnEXITClick( wxCommandEvent& event )
{
	Close();
}


/*!
 * wxEVT_COMMAND_MENU_SELECTED event handler for ID_MOZILLA_LIKE_ABOUTBOX
 */

void wxAboutBoxTestMainFrame::OnMOZILLALIKEABOUTBOXClick( wxCommandEvent& event )
{
	// Create About box 
	wxMozillaLikeAboutBoxDialog * dlg = new wxMozillaLikeAboutBoxDialog(this);
	// Set application name
	dlg->SetAppName(wxTheApp->GetAppName());
	// Set application version
	dlg->SetVersion(wxT("1.0.0 b1"));
	// Set copyright message
	dlg->SetCopyright(wxString::Format(wxT("%c %i %s"),
		(wxChar) 0x00A9, wxDateTime::Now().GetYear(),
		_("Volodymir (T-Rex) Tryapichko. All rights reserved. Please contact author if you have any copyright-related questions.")));
	// Set build info message. This is optional step. If you don't specify build info message then
	// default one will be used
	dlg->SetCustomBuildInfo(wxString::Format(wxT("%s. %s"),
		wxMozillaLikeAboutBoxDialog::GetBuildInfo(wxMozillaLikeAboutBoxDialog::wxBUILDINFO_LONG).GetData(),
		_("Compiled by T-Rex personally :)")));
	// Set header bitmap
	dlg->SetHeaderBitmap(wxGetBitmapFromMemory(header_png, sizeof(header_png)));
	// Apply changes
	dlg->ApplyInfo();
	// Show dialog
	dlg->ShowModal();
	// Destroy dialog
	dlg->Destroy();
}


/*!
 * wxEVT_COMMAND_MENU_SELECTED event handler for wxID_ABOUT
 */

void wxAboutBoxTestMainFrame::OnABOUTClick( wxCommandEvent& event )
{
	// This object will contain all information displayed in About box
	wxAboutDialogInfo info;
	// Call of AddDeveloper() method adds a record to list of developers
	info.AddDeveloper(_("John Doe"));
	// Call of AddDocWriter() method adds a record to list of documentation writers
	info.AddDocWriter(_("Donald Duck"));
	// Call of AddArtist() method adds a record to list of artists
	info.AddArtist(_("Scrooge Mc.Duck"));
	// Call of AddTranslator() method adds a record to list of translators
	info.AddTranslator(_("Mickey Mouse"));
	// This method adds application description.
	info.SetDescription(_("Sample wxWidgets application for testing wxAboutBox() function."));
	// This method sets application version string
	info.SetVersion(wxT("1.0.0 beta 1"));
	// SetName() method sets application name displayed in About box. 
	// It is better to pass wxApp::GetAppName() to this method
	info.SetName(wxTheApp->GetAppName());
	// Sets application Web-site URL
	info.SetWebSite(wxT("http://wxwidgets.info"));
	// Sets the icon which will be displayed in About box.
	info.SetIcon(wxICON(wxICON_AAA));
	// Sets application license string. Only wxGTK port has native way of 
	// displaying application license. All other ports will use generic way for this purpose.
	info.SetLicence(_("Public Domain"));

	// At last, we can display about box
	wxAboutBox(info);
}
