/////////////////////////////////////////////////////////////////////////////
// Name:        wxAboutBoxTestMainFrame.h
// Purpose:     
// Author:      Volodymir (T-Rex) Tryapichko
// Modified by: 
// Created:     24/01/2009 15:45:30
// RCS-ID:      
// Copyright:   Copyright (c) Volodymir (T-Rex) Tryapichko, 2009
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (unregistered), 24/01/2009 15:45:30

#ifndef _WXABOUTBOXTESTMAINFRAME_H_
#define _WXABOUTBOXTESTMAINFRAME_H_


/*!
 * Includes
 */

////@begin includes
#include "wx/frame.h"
#include "wx/statusbr.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define SYMBOL_WXABOUTBOXTESTMAINFRAME_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX
#define SYMBOL_WXABOUTBOXTESTMAINFRAME_TITLE _("wxAboutBoxTestMainFrame")
#define SYMBOL_WXABOUTBOXTESTMAINFRAME_IDNAME ID_WXABOUTBOXTESTMAINFRAME
#define SYMBOL_WXABOUTBOXTESTMAINFRAME_SIZE wxSize(400, 300)
#define SYMBOL_WXABOUTBOXTESTMAINFRAME_POSITION wxDefaultPosition
////@end control identifiers


/*!
 * wxAboutBoxTestMainFrame class declaration
 */

class wxAboutBoxTestMainFrame: public wxFrame
{    
    DECLARE_CLASS( wxAboutBoxTestMainFrame )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    wxAboutBoxTestMainFrame();
    wxAboutBoxTestMainFrame( wxWindow* parent, wxWindowID id = SYMBOL_WXABOUTBOXTESTMAINFRAME_IDNAME, const wxString& caption = SYMBOL_WXABOUTBOXTESTMAINFRAME_TITLE, const wxPoint& pos = SYMBOL_WXABOUTBOXTESTMAINFRAME_POSITION, const wxSize& size = SYMBOL_WXABOUTBOXTESTMAINFRAME_SIZE, long style = SYMBOL_WXABOUTBOXTESTMAINFRAME_STYLE );

    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_WXABOUTBOXTESTMAINFRAME_IDNAME, const wxString& caption = SYMBOL_WXABOUTBOXTESTMAINFRAME_TITLE, const wxPoint& pos = SYMBOL_WXABOUTBOXTESTMAINFRAME_POSITION, const wxSize& size = SYMBOL_WXABOUTBOXTESTMAINFRAME_SIZE, long style = SYMBOL_WXABOUTBOXTESTMAINFRAME_STYLE );

    /// Destructor
    ~wxAboutBoxTestMainFrame();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin wxAboutBoxTestMainFrame event handler declarations

    /// wxEVT_COMMAND_MENU_SELECTED event handler for wxID_EXIT
    void OnEXITClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_MENU_SELECTED event handler for ID_MOZILLA_LIKE_ABOUTBOX
    void OnMOZILLALIKEABOUTBOXClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_MENU_SELECTED event handler for wxID_ABOUT
    void OnABOUTClick( wxCommandEvent& event );

////@end wxAboutBoxTestMainFrame event handler declarations

////@begin wxAboutBoxTestMainFrame member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end wxAboutBoxTestMainFrame member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin wxAboutBoxTestMainFrame member variables
    /// Control identifiers
    enum {
        ID_WXABOUTBOXTESTMAINFRAME = 10000,
        ID_PANEL = 10001,
        ID_STATUSBAR = 10002,
        ID_MOZILLA_LIKE_ABOUTBOX = 10005
    };
////@end wxAboutBoxTestMainFrame member variables
};

#endif
    // _WXABOUTBOXTESTMAINFRAME_H_
