// -*- C++ -*-
//
// generated by wxGlade 0.8.2 on Mon Nov 26 17:05:49 2018
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#include <wx/wx.h>
#include "EventTable.h"

// begin wxGlade: ::extracode
// end wxGlade


EventTable::EventTable(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxFrame(parent, id, title, pos, size, wxDEFAULT_FRAME_STYLE)
{
    // begin wxGlade: EventTable::EventTable
    SetSize(wxSize(900, 300));
    frame_2_menubar = new wxMenuBar();
    wxMenu *wxglade_tmp_menu;
    wxglade_tmp_menu = new wxMenu();
    wxglade_tmp_menu->Append(wxID_SAVEAS, wxT("Save As..."), wxEmptyString);
    Connect(wxID_SAVEAS, wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(EventTable::handle_save));
    wxglade_tmp_menu->Append(wxID_CLOSE, wxT("Close"), wxEmptyString);
    Connect(wxID_CLOSE, wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(EventTable::handle_done));
    frame_2_menubar->Append(wxglade_tmp_menu, wxT("File"));
    SetMenuBar(frame_2_menubar);
    data_grid = new wxGrid(this, wxID_ANY);

    set_properties();
    do_layout();
    // end wxGlade
}


void EventTable::set_properties()
{
    // begin wxGlade: EventTable::set_properties
    SetTitle(wxT("frame_2"));
    // end wxGlade
}


void EventTable::do_layout()
{
    // begin wxGlade: EventTable::do_layout
    wxBoxSizer* sizer_8 = new wxBoxSizer(wxVERTICAL);
    sizer_8->Add(data_grid, 1, wxEXPAND, 0);
    SetSizer(sizer_8);
    Layout();
    // end wxGlade
}


BEGIN_EVENT_TABLE(EventTable, wxFrame)
    // begin wxGlade: EventTable::event_table
    // end wxGlade
END_EVENT_TABLE();


void EventTable::handle_save(wxCommandEvent &event)  // wxGlade: EventTable.<event_handler>
{
    event.Skip();
    // notify the user that he hasn't implemented the event handler yet
    wxLogDebug(wxT("Event handler (EventTable::handle_save) not implemented yet"));
}

void EventTable::handle_done(wxCommandEvent &event)  // wxGlade: EventTable.<event_handler>
{
    event.Skip();
    // notify the user that he hasn't implemented the event handler yet
    wxLogDebug(wxT("Event handler (EventTable::handle_done) not implemented yet"));
}


// wxGlade: add EventTable event handlers

