// -*- C++ -*- generated by wxGlade 0.6.3 on Thu Sep 22 13:41:38 2011

#include "EventTable.h"

// begin wxGlade: ::extracode

// end wxGlade


EventTable::EventTable(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxFrame(parent, id, title, pos, size, wxDEFAULT_FRAME_STYLE)
{
    // begin wxGlade: EventTable::EventTable
    data_grid = new wxGrid(this, wxID_ANY);
    frame_2_menubar = new wxMenuBar();
    wxMenu* wxglade_tmp_menu_1 = new wxMenu();
    wxglade_tmp_menu_1->Append(wxID_SAVEAS, wxT("Save As..."), wxEmptyString, wxITEM_NORMAL);
    wxglade_tmp_menu_1->Append(wxID_CLOSE, wxT("Close"), wxEmptyString, wxITEM_NORMAL);
    frame_2_menubar->Append(wxglade_tmp_menu_1, wxT("File"));
    SetMenuBar(frame_2_menubar);

    set_properties();
    do_layout();
    // end wxGlade
}


BEGIN_EVENT_TABLE(EventTable, wxFrame)
    // begin wxGlade: EventTable::event_table
    EVT_MENU(wxID_SAVEAS, EventTable::handle_save)
    EVT_MENU(wxID_CLOSE, EventTable::handle_done)
    // end wxGlade
END_EVENT_TABLE();


void EventTable::handle_save(wxCommandEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (EventTable::handle_save) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


void EventTable::handle_done(wxCommandEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (EventTable::handle_done) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


// wxGlade: add EventTable event handlers


void EventTable::set_properties()
{
    // begin wxGlade: EventTable::set_properties
    SetTitle(wxT("frame_2"));
    SetSize(wxSize(900, 300));
    // end wxGlade
}


void EventTable::do_layout()
{
    // begin wxGlade: EventTable::do_layout
    wxBoxSizer* sizer_8 = new wxBoxSizer(wxVERTICAL);
    sizer_8->Add(data_grid, 1, wxEXPAND, 0);
    SetSizer(sizer_8);
    Layout();
    // end wxGlade
}

