// -*- C++ -*- generated by wxGlade 0.6.3 on Fri Sep 16 13:45:37 2011

#include <wx/wx.h>
#include <wx/image.h>

#ifndef EVENTCANVAS_H
#define EVENTCANVAS_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
#include <EventCanvasApp.h>

// end wxGlade


class EventCanvas: public EventCanvasApp {
public:
    // begin wxGlade: EventCanvas::ids
    // end wxGlade

    EventCanvas(wxWindow* parent, int id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);

private:
    // begin wxGlade: EventCanvas::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: EventCanvas::attributes
    // end wxGlade
}; // wxGlade: end class


#endif // EVENTCANVAS_H
