// -*- C++ -*-
//
// generated by wxGlade 0.9.5 on Thu May  7 16:48:42 2020
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef EVENTTABLE_H
#define EVENTTABLE_H

#include <wx/wx.h>
#include <wx/image.h>

// begin wxGlade: ::dependencies
#include <wx/grid.h>
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class EventTable: public wxFrame {
public:
    // begin wxGlade: EventTable::ids
    // end wxGlade

    EventTable(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: EventTable::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: EventTable::attributes
    wxMenuBar* frame_2_menubar;
    wxGrid* data_grid;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    void handle_save(wxCommandEvent &event); // wxGlade: <event_handler>
    void handle_done(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // EVENTTABLE_H
