// -*- C++ -*- generated by wxGlade 0.6.3 on Fri Sep 16 13:45:37 2011

#include "EventTable.h"

// begin wxGlade: ::extracode

// end wxGlade


EventTable::EventTable(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxFrame(parent, id, title, pos, size, wxDEFAULT_FRAME_STYLE)
{
    // begin wxGlade: EventTable::EventTable
    data_grid = new wxGrid(this, wxID_ANY);
    done_button = new wxButton(this, wxID_OK, wxT("Done"));
    static_line_3 = new wxStaticLine(this, wxID_ANY);
    save_button = new wxButton(this, wxID_SAVEAS, wxT("Save..."));
    static_line_4 = new wxStaticLine(this, wxID_ANY);
    cancel_button = new wxButton(this, wxID_CANCEL, wxT("Cancel"));

    set_properties();
    do_layout();
    // end wxGlade
}


BEGIN_EVENT_TABLE(EventTable, wxFrame)
    // begin wxGlade: EventTable::event_table
    EVT_BUTTON(wxID_OK, EventTable::handle_done)
    EVT_BUTTON(wxID_SAVEAS, EventTable::handle_save)
    EVT_BUTTON(wxID_CANCEL, EventTable::handle_cancel)
    // end wxGlade
END_EVENT_TABLE();


void EventTable::handle_done(wxCommandEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (EventTable::handle_done) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


void EventTable::handle_save(wxCommandEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (EventTable::handle_save) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


void EventTable::handle_cancel(wxCommandEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (EventTable::handle_cancel) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


// wxGlade: add EventTable event handlers


void EventTable::set_properties()
{
    // begin wxGlade: EventTable::set_properties
    SetTitle(wxT("frame_2"));
    SetSize(wxSize(800, 300));
    // end wxGlade
}


void EventTable::do_layout()
{
    // begin wxGlade: EventTable::do_layout
    wxBoxSizer* sizer_8 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_9 = new wxBoxSizer(wxHORIZONTAL);
    sizer_8->Add(data_grid, 1, wxEXPAND, 0);
    sizer_9->Add(done_button, 0, 0, 0);
    sizer_9->Add(static_line_3, 5, wxEXPAND, 0);
    sizer_9->Add(save_button, 0, 0, 0);
    sizer_9->Add(static_line_4, 5, wxEXPAND, 0);
    sizer_9->Add(cancel_button, 0, wxRIGHT, 0);
    sizer_8->Add(sizer_9, 0, wxEXPAND, 0);
    SetSizer(sizer_8);
    Layout();
    // end wxGlade
}

