// -*- C++ -*- generated by wxGlade HG on Tue May 10 09:45:23 2011

#include "EventCanvas.h"

// begin wxGlade: ::extracode

// end wxGlade


EventCanvas::EventCanvas(wxWindow* parent, int id, const wxPoint& pos, const wxSize& size, long style):
    EventCanvasApp(parent, id, pos, size, wxDOUBLE_BORDER|wxRAISED_BORDER|wxTAB_TRAVERSAL)
{
    // begin wxGlade: EventCanvas::EventCanvas

    set_properties();
    do_layout();
    // end wxGlade
}


void EventCanvas::set_properties()
{
    // begin wxGlade: EventCanvas::set_properties
    SetScrollRate(25, 25);
    // end wxGlade
}


void EventCanvas::do_layout()
{
    // begin wxGlade: EventCanvas::do_layout
    // end wxGlade
}

