// -*- C++ -*-
//
// generated by wxGlade 0.9.5 on Fri May 29 14:58:35 2020
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#include <wx/wx.h>
#include "EventCanvas.h"

// begin wxGlade: ::extracode
// end wxGlade


EventCanvas::EventCanvas(wxWindow* parent, wxWindowID id, const wxPoint& pos, const wxSize& size, long style):
    EventCanvasApp(parent, id, pos, size, wxBORDER_RAISED|wxTAB_TRAVERSAL)
{
    // begin wxGlade: EventCanvas::EventCanvas

    set_properties();
    do_layout();
    // end wxGlade
}


void EventCanvas::set_properties()
{
    // begin wxGlade: EventCanvas::set_properties
    SetScrollRate(10, 10);
    // end wxGlade
}


void EventCanvas::do_layout()
{
    // begin wxGlade: EventCanvas::do_layout
    // end wxGlade
}

