// -*- C++ -*- generated by wxGlade HG on Wed May 11 19:03:42 2011

#include <wx/wx.h>
#include <wx/image.h>
#include "MainFrame.h"



class MyApp: public wxApp {
public:
    bool OnInit();
};

IMPLEMENT_APP(MyApp)

bool MyApp::OnInit()
{
    wxInitAllImageHandlers();
    MainFrame* frame_1 = new MainFrame(NULL, wxID_ANY, wxEmptyString);
    SetTopWindow(frame_1);
    frame_1->Show();
    return true;
}
