// -*- C++ -*- generated by wxGlade 0.6.3 on Thu Sep 22 13:41:38 2011

#include <wx/wx.h>
#include <wx/image.h>

#ifndef MAINFRAME_H
#define MAINFRAME_H

// begin wxGlade: ::dependencies
#include <wx/treectrl.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include "EventCanvas.h"
// end wxGlade

// begin wxGlade: ::extracode
#include <EventCanvasApp.h>

// end wxGlade


class MainFrame: public wxFrame {
public:
    // begin wxGlade: MainFrame::ids
    enum {
        FileOpen_id = wxID_HIGHEST + 1014,
        DataSetAnnotation_id = wxID_HIGHEST + 1015,
        EventSearch_id = wxID_HIGHEST + 1016,
        MenuRefresh_id = wxID_HIGHEST + 1017,
        EventData_id = wxID_HIGHEST + 1018,
        CursorMenu_id = wxID_HIGHEST + 1019,
        ResetCursor_id = wxID_HIGHEST + 1020,
        SortEventName_id = wxID_HIGHEST + 1021,
        SortNumOccur_id = wxID_HIGHEST + 1022,
        SortAvg_id = wxID_HIGHEST + 1023,
        SortMaxDuration_id = wxID_HIGHEST + 1024,
        SortMinDuration_id = wxID_HIGHEST + 1025,
        SortPctAct_id = wxID_HIGHEST + 1026,
        ColorPicker_id = wxID_HIGHEST + 1027,
        move_top_id = wxID_HIGHEST + 1045,
        move_bottom_id = wxID_HIGHEST + 1046,
        filter_events_id = wxID_HIGHEST + 1047,
        timeline_endpoint_update_id = wxID_HIGHEST + 1051,
        set_1_id = wxID_HIGHEST + 1053,
        spin_1_id = wxID_HIGHEST + 1055,
        set_2_id = wxID_HIGHEST + 1057,
        spin_2_id = wxID_HIGHEST + 1059
    };
    // end wxGlade

    MainFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: MainFrame::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: MainFrame::attributes
    wxMenuBar* frame_1_menubar;
    wxToolBar* frame_1_toolbar;
    wxTreeCtrl* g_EventList;
    EventCanvas* g_EventFrame;
    wxTextCtrl* g_StartTime;
    wxPanel* g_timeScale;
    wxTextCtrl* g_EndTime;
    wxStaticText* g_TotalEventCount;
    wxStaticLine* static_line_1;
    wxTextCtrl* g_EventInfo;
    wxTextCtrl* g_CommentText;
    wxStaticLine* static_line_2;
    wxStaticText* label_1;
    wxTextCtrl* g_Curs1Time;
    wxSpinButton* spin_button_1;
    wxStaticText* label_2;
    wxTextCtrl* g_Curs2Time;
    wxSpinButton* spin_button_2;
    wxStaticText* g_CursDtime;
    wxStaticLine* static_line_2_copy;
    wxScrolledWindow* panel_1;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void FileOpenHandler(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void SaveHandler(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void SaveAsHandler(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void QuitHandler(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void EditDataSetAnnotationHandler(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void ZoomInHandler(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void ZoomOutHandler(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void ZoomFillHandler(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void RefreshHandler(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void EventDataHandler(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void CursorMenuHandler(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void ResetCursorHandler(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void SortEventNameHandler(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void SortNumOccurHandler(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void SortAvgHandler(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void SortMaxDurationHandler(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void SortMinDurationHandler(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void SortPctActHandler(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void ColorPickerHandler(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void AboutHandler(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void handle_move_top(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void handle_move_up(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void handle_move_down(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void handle_move_bottom(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void handle_filter_events(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void handle_enter_timeline(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void Curs1Set(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void Curs1Down(wxSpinEvent &event); // wxGlade: <event_handler>
    virtual void Curs1Up(wxSpinEvent &event); // wxGlade: <event_handler>
    virtual void Curs2Set(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void Curs2Down(wxSpinEvent &event); // wxGlade: <event_handler>
    virtual void Curs2Up(wxSpinEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // MAINFRAME_H
