// -*- C++ -*-
//
// generated by wxGlade 0.8.2 on Mon Nov 26 17:05:49 2018
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#include <wx/wx.h>
#include "RT_MainFrame.h"

// begin wxGlade: ::extracode

#include "resources/martini.xpm"
#include "resources/Bottom.xpm"
#include "resources/down_arrow.xpm"
#include "resources/Expand.xpm"
#include "resources/Filter.xpm"
#include "resources/left_arrow.xpm"
#include "resources/Linux.xpm"
#include "resources/right_arrow.xpm"
#include "resources/Top.xpm"
#include "resources/up_arrow.xpm"
#include "resources/zoom_in.xpm"
#include "resources/zoom_out.xpm"
// end wxGlade


RT_MainFrame::RT_MainFrame(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxFrame(parent, id, title, pos, size, wxDEFAULT_FRAME_STYLE)
{
    // begin wxGlade: RT_MainFrame::RT_MainFrame
    SetSize(wxSize(1530, 800));
    frame_1_menubar = new wxMenuBar();
    FileMenu = new wxMenu();
    FileOpen = FileMenu->Append(FileOpen_id, wxT("Load events"), wxEmptyString);
    Connect(FileOpen_id, wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(RT_MainFrame::FileOpenHandler));
    FileMenu->Append(wxID_ANY, wxT("Merge events"), wxT("Merge events into current data set."));
    FileMenu->Append(wxID_SAVE, wxT("Save"), wxT("Save dataset"));
    Connect(wxID_SAVE, wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(RT_MainFrame::SaveHandler));
    FileMenu->Append(wxID_SAVEAS, wxT("Save As..."), wxT("Save data set under a new name"));
    Connect(wxID_SAVEAS, wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(RT_MainFrame::SaveAsHandler));
    FileQuit = FileMenu->Append(wxID_EXIT, wxT("Quit"), wxEmptyString);
    Connect(wxID_EXIT, wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(RT_MainFrame::QuitHandler));
    frame_1_menubar->Append(FileMenu, wxT("File"));
    EditMenu = new wxMenu();
    EditMenu->Append(wxID_UNDO, wxT("Undo"), wxEmptyString);
    EditMenu->Append(wxID_CUT, wxT("Cut"), wxEmptyString);
    EditMenu->Append(wxID_COPY, wxT("Copy"), wxEmptyString);
    EditMenu->Append(wxID_PASTE, wxT("Paste"), wxEmptyString);
    EditMenu->Append(DataSetAnnotation_id, wxT("Edit Data Set Annotation"), wxEmptyString);
    Connect(DataSetAnnotation_id, wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(RT_MainFrame::EditDataSetAnnotationHandler));
    EditMenu->Append(EventSearch_id, wxT("Search"), wxT("Search for event names"));
    frame_1_menubar->Append(EditMenu, wxT("Edit"));
    ViewMenu = new wxMenu();
    ZoomIn = ViewMenu->Append(wxID_ZOOM_IN, wxT("Zoom in"), wxEmptyString);
    Connect(wxID_ZOOM_IN, wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(RT_MainFrame::ZoomInHandler));
    ZoomOut = ViewMenu->Append(wxID_ZOOM_OUT, wxT("Zoom out"), wxEmptyString);
    Connect(wxID_ZOOM_OUT, wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(RT_MainFrame::ZoomOutHandler));
    ViewMenu->Append(wxID_ZOOM_FIT, wxT("Zoom to fill window"), wxEmptyString);
    Connect(wxID_ZOOM_FIT, wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(RT_MainFrame::ZoomFillHandler));
    ViewMenu->Append(MenuRefresh_id, wxT("Refresh"), wxEmptyString);
    Connect(MenuRefresh_id, wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(RT_MainFrame::RefreshHandler));
    EventDataSummary = ViewMenu->Append(EventData_id, wxT("Event Data Summary"), wxEmptyString);
    Connect(EventData_id, wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(RT_MainFrame::EventDataHandler));
    CursorMenu = ViewMenu->Append(CursorMenu_id, wxT("Cursor display"), wxEmptyString, wxITEM_CHECK);
    Connect(CursorMenu_id, wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(RT_MainFrame::CursorMenuHandler));
    ResetCursors = ViewMenu->Append(ResetCursor_id, wxT("Reset cursors"), wxEmptyString);
    Connect(ResetCursor_id, wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(RT_MainFrame::ResetCursorHandler));
    wxMenu* ViewMenu_sub = new wxMenu();
    ViewMenu_sub->Append(SortEventName_id, wxT("Event Name"), wxEmptyString);
    Connect(SortEventName_id, wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(RT_MainFrame::SortEventNameHandler));
    ViewMenu_sub->Append(SortNumOccur_id, wxT("Num Occurrences"), wxEmptyString);
    Connect(SortNumOccur_id, wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(RT_MainFrame::SortNumOccurHandler));
    ViewMenu_sub->Append(SortAvg_id, wxT("Average Duration"), wxEmptyString);
    Connect(SortAvg_id, wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(RT_MainFrame::SortAvgHandler));
    ViewMenu_sub->Append(SortMaxDuration_id, wxT("Max Duration"), wxEmptyString);
    Connect(SortMaxDuration_id, wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(RT_MainFrame::SortMaxDurationHandler));
    ViewMenu_sub->Append(SortMinDuration_id, wxT("Min Duration"), wxEmptyString);
    Connect(SortMinDuration_id, wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(RT_MainFrame::SortMinDurationHandler));
    ViewMenu_sub->Append(SortPctAct_id, wxT("Percent Active"), wxEmptyString);
    Connect(SortPctAct_id, wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(RT_MainFrame::SortPctActHandler));
    ViewMenu->Append(wxID_ANY, wxT("Sort By"), ViewMenu_sub, wxEmptyString);
    frame_1_menubar->Append(ViewMenu, wxT("View"));
    ToolsMenu = new wxMenu();
    ToolsMenu->Append(ColorPicker_id, wxT("Color"), wxEmptyString);
    Connect(ColorPicker_id, wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(RT_MainFrame::ColorPickerHandler));
    frame_1_menubar->Append(ToolsMenu, wxT("Tools"));
    HelpMenu = new wxMenu();
    AboutMenu = HelpMenu->Append(wxID_ABOUT, wxT("About"), wxEmptyString);
    Connect(wxID_ABOUT, wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(RT_MainFrame::AboutHandler));
    frame_1_menubar->Append(HelpMenu, wxT("Help"));
    SetMenuBar(frame_1_menubar);
    frame_1_toolbar = new wxToolBar(this, -1);
    SetToolBar(frame_1_toolbar);
    frame_1_toolbar->AddTool(wxID_ZOOM_IN, wxT("Zoom In"), zoom_in_xpm, wxNullBitmap, wxITEM_NORMAL, wxT("Zoom in"), wxEmptyString);
    frame_1_toolbar->AddTool(wxID_ZOOM_OUT, wxT("Zoom Out"), zoom_out_xpm, wxNullBitmap, wxITEM_NORMAL, wxT("Zoom out"), wxEmptyString);
    frame_1_toolbar->AddTool(wxID_ZOOM_FIT, wxT("Zoom Fit"), Expand_xpm, wxNullBitmap, wxITEM_NORMAL, wxT("Zoom to fit window"), wxEmptyString);
    frame_1_toolbar->AddSeparator();
    frame_1_toolbar->AddTool(move_top_id, wxT("Move to Top"), Top_xpm, wxNullBitmap, wxITEM_NORMAL, wxT("Move event to top of list"), wxEmptyString);
    frame_1_toolbar->AddTool(wxID_UP, wxT("Move Up"), up_arrow_xpm, wxNullBitmap, wxITEM_NORMAL, wxT("Move event up one row"), wxEmptyString);
    frame_1_toolbar->AddTool(wxID_DOWN, wxT("Move Down"), down_arrow_xpm, wxNullBitmap, wxITEM_NORMAL, wxT("Move event down one row"), wxEmptyString);
    frame_1_toolbar->AddTool(move_bottom_id, wxT("Move to Bottom"), Bottom_xpm, wxNullBitmap, wxITEM_NORMAL, wxT("Move event to bottom of list"), wxEmptyString);
    frame_1_toolbar->AddTool(filter_events_id, wxT("Filter empty events"), Filter_xpm, wxNullBitmap, wxITEM_CHECK, wxT("Filter out empty events"), wxEmptyString);
    frame_1_toolbar->AddSeparator();
    frame_1_toolbar->AddTool(ResetCursor_id, wxT("Reset Cursors"), Linux_xpm, wxNullBitmap, wxITEM_NORMAL, wxEmptyString, wxEmptyString);
    frame_1_toolbar->AddTool(wxID_ANY, wxT("Party Time"), martini_xpm, wxNullBitmap, wxITEM_NORMAL, wxEmptyString, wxEmptyString);
    frame_1_toolbar->Realize();
    g_EventList = new wxTreeCtrl(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_SUNKEN|wxTR_DEFAULT_STYLE|wxTR_HAS_BUTTONS|wxTR_NO_LINES);
    g_EventFrame = new EventCanvas(this, wxID_ANY);
    g_StartTime = new wxTextCtrl(this, timeline_endpoint_update_id, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxTE_PROCESS_ENTER);
    g_timeScale = new wxPanel(this, wxID_ANY);
    g_EndTime = new wxTextCtrl(this, timeline_endpoint_update_id, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxTE_PROCESS_ENTER);
    g_TotalEventCount = new wxStaticText(this, wxID_ANY, wxT("Total events: 0"));
    static_line_1 = new wxStaticLine(this, wxID_ANY);
    g_EventInfo = new wxTextCtrl(this, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxHSCROLL|wxTE_MULTILINE|wxTE_READONLY);
    g_CommentText = new wxTextCtrl(this, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxHSCROLL|wxTE_CHARWRAP|wxTE_MULTILINE|wxTE_PROCESS_ENTER);
    static_line_2 = new wxStaticLine(this, wxID_ANY);
    label_1 = new wxStaticText(this, wxID_ANY, wxT("Cursor 1"));
    g_Curs1Time = new wxTextCtrl(this, set_1_id, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxTE_PROCESS_ENTER);
    spin_button_1 = new wxSpinButton(this, spin_1_id, wxDefaultPosition, wxDefaultSize, wxSP_WRAP);
    label_2 = new wxStaticText(this, wxID_ANY, wxT("Cursor 2"));
    g_Curs2Time = new wxTextCtrl(this, set_2_id, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxTE_PROCESS_ENTER);
    spin_button_2 = new wxSpinButton(this, spin_2_id, wxDefaultPosition, wxDefaultSize, wxSP_WRAP);
    g_CursDtime = new wxStaticText(this, wxID_ANY, wxT("Delta time:"));
    static_line_2_copy = new wxStaticLine(this, wxID_ANY);
    panel_1 = new wxScrolledWindow(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL);

    set_properties();
    do_layout();
    // end wxGlade
}


void RT_MainFrame::set_properties()
{
    // begin wxGlade: RT_MainFrame::set_properties
    SetTitle(wxT("Right Track Event Viewer"));
    g_TotalEventCount->SetMinSize(wxSize(150, 17));
    static_line_1->SetBackgroundColour(wxColour(255, 127, 0));
    static_line_1->SetForegroundColour(wxColour(255, 127, 0));
    static_line_2->SetBackgroundColour(wxColour(255, 127, 0));
    static_line_2->SetForegroundColour(wxColour(255, 127, 0));
    static_line_2_copy->SetBackgroundColour(wxColour(255, 127, 0));
    static_line_2_copy->SetForegroundColour(wxColour(255, 127, 0));
    // end wxGlade
}


void RT_MainFrame::do_layout()
{
    // begin wxGlade: RT_MainFrame::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_2 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_7 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_6 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_3 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_4 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_5 = new wxBoxSizer(wxHORIZONTAL);
    sizer_3->Add(g_EventList, 1, wxEXPAND, 0);
    sizer_4->Add(g_EventFrame, 1, wxALL|wxEXPAND, 3);
    sizer_5->Add(g_StartTime, 1, wxEXPAND, 0);
    sizer_5->Add(g_timeScale, 6, 0, 0);
    sizer_5->Add(g_EndTime, 1, wxEXPAND, 0);
    sizer_4->Add(sizer_5, 0, wxEXPAND, 0);
    sizer_3->Add(sizer_4, 13, wxEXPAND, 0);
    sizer_1->Add(sizer_3, 1, wxEXPAND, 0);
    sizer_2->Add(g_TotalEventCount, 0, wxEXPAND, 0);
    sizer_2->Add(static_line_1, 0, wxEXPAND, 0);
    sizer_2->Add(g_EventInfo, 5, wxEXPAND, 0);
    sizer_2->Add(g_CommentText, 5, wxEXPAND, 0);
    sizer_2->Add(static_line_2, 0, wxEXPAND, 0);
    sizer_6->Add(label_1, 0, 0, 0);
    sizer_6->Add(g_Curs1Time, 0, 0, 0);
    sizer_6->Add(spin_button_1, 0, 0, 0);
    sizer_2->Add(sizer_6, 1, 0, 0);
    sizer_7->Add(label_2, 0, 0, 0);
    sizer_7->Add(g_Curs2Time, 0, 0, 0);
    sizer_7->Add(spin_button_2, 0, 0, 0);
    sizer_2->Add(sizer_7, 1, 0, 0);
    sizer_2->Add(g_CursDtime, 1, wxEXPAND, 0);
    sizer_2->Add(static_line_2_copy, 0, wxEXPAND, 0);
    sizer_2->Add(panel_1, 6, wxEXPAND, 0);
    sizer_1->Add(sizer_2, 0, wxEXPAND, 0);
    SetSizer(sizer_1);
    Layout();
    // end wxGlade
}


BEGIN_EVENT_TABLE(RT_MainFrame, wxFrame)
    // begin wxGlade: RT_MainFrame::event_table
    EVT_TOOL(move_top_id, RT_MainFrame::handle_move_top)
    EVT_TOOL(wxID_UP, RT_MainFrame::handle_move_up)
    EVT_TOOL(wxID_DOWN, RT_MainFrame::handle_move_down)
    EVT_TOOL(move_bottom_id, RT_MainFrame::handle_move_bottom)
    EVT_TOOL(filter_events_id, RT_MainFrame::handle_filter_events)
    EVT_TEXT_ENTER(timeline_endpoint_update_id, RT_MainFrame::handle_enter_timeline)
    EVT_TEXT_ENTER(timeline_endpoint_update_id, RT_MainFrame::handle_enter_timeline)
    EVT_TEXT_ENTER(set_1_id, RT_MainFrame::Curs1Set)
    EVT_SPIN_DOWN(spin_1_id, RT_MainFrame::Curs1Down)
    EVT_SPIN_UP(spin_1_id, RT_MainFrame::Curs1Up)
    EVT_TEXT_ENTER(set_2_id, RT_MainFrame::Curs2Set)
    EVT_SPIN_DOWN(spin_2_id, RT_MainFrame::Curs2Down)
    EVT_SPIN_UP(spin_2_id, RT_MainFrame::Curs2Up)
    // end wxGlade
END_EVENT_TABLE();


void RT_MainFrame::FileOpenHandler(wxCommandEvent &event)  // wxGlade: RT_MainFrame.<event_handler>
{
    event.Skip();
    // notify the user that he hasn't implemented the event handler yet
    wxLogDebug(wxT("Event handler (RT_MainFrame::FileOpenHandler) not implemented yet"));
}

void RT_MainFrame::SaveHandler(wxCommandEvent &event)  // wxGlade: RT_MainFrame.<event_handler>
{
    event.Skip();
    // notify the user that he hasn't implemented the event handler yet
    wxLogDebug(wxT("Event handler (RT_MainFrame::SaveHandler) not implemented yet"));
}

void RT_MainFrame::SaveAsHandler(wxCommandEvent &event)  // wxGlade: RT_MainFrame.<event_handler>
{
    event.Skip();
    // notify the user that he hasn't implemented the event handler yet
    wxLogDebug(wxT("Event handler (RT_MainFrame::SaveAsHandler) not implemented yet"));
}

void RT_MainFrame::QuitHandler(wxCommandEvent &event)  // wxGlade: RT_MainFrame.<event_handler>
{
    event.Skip();
    // notify the user that he hasn't implemented the event handler yet
    wxLogDebug(wxT("Event handler (RT_MainFrame::QuitHandler) not implemented yet"));
}

void RT_MainFrame::EditDataSetAnnotationHandler(wxCommandEvent &event)  // wxGlade: RT_MainFrame.<event_handler>
{
    event.Skip();
    // notify the user that he hasn't implemented the event handler yet
    wxLogDebug(wxT("Event handler (RT_MainFrame::EditDataSetAnnotationHandler) not implemented yet"));
}

void RT_MainFrame::ZoomInHandler(wxCommandEvent &event)  // wxGlade: RT_MainFrame.<event_handler>
{
    event.Skip();
    // notify the user that he hasn't implemented the event handler yet
    wxLogDebug(wxT("Event handler (RT_MainFrame::ZoomInHandler) not implemented yet"));
}

void RT_MainFrame::ZoomOutHandler(wxCommandEvent &event)  // wxGlade: RT_MainFrame.<event_handler>
{
    event.Skip();
    // notify the user that he hasn't implemented the event handler yet
    wxLogDebug(wxT("Event handler (RT_MainFrame::ZoomOutHandler) not implemented yet"));
}

void RT_MainFrame::ZoomFillHandler(wxCommandEvent &event)  // wxGlade: RT_MainFrame.<event_handler>
{
    event.Skip();
    // notify the user that he hasn't implemented the event handler yet
    wxLogDebug(wxT("Event handler (RT_MainFrame::ZoomFillHandler) not implemented yet"));
}

void RT_MainFrame::RefreshHandler(wxCommandEvent &event)  // wxGlade: RT_MainFrame.<event_handler>
{
    event.Skip();
    // notify the user that he hasn't implemented the event handler yet
    wxLogDebug(wxT("Event handler (RT_MainFrame::RefreshHandler) not implemented yet"));
}

void RT_MainFrame::EventDataHandler(wxCommandEvent &event)  // wxGlade: RT_MainFrame.<event_handler>
{
    event.Skip();
    // notify the user that he hasn't implemented the event handler yet
    wxLogDebug(wxT("Event handler (RT_MainFrame::EventDataHandler) not implemented yet"));
}

void RT_MainFrame::CursorMenuHandler(wxCommandEvent &event)  // wxGlade: RT_MainFrame.<event_handler>
{
    event.Skip();
    // notify the user that he hasn't implemented the event handler yet
    wxLogDebug(wxT("Event handler (RT_MainFrame::CursorMenuHandler) not implemented yet"));
}

void RT_MainFrame::ResetCursorHandler(wxCommandEvent &event)  // wxGlade: RT_MainFrame.<event_handler>
{
    event.Skip();
    // notify the user that he hasn't implemented the event handler yet
    wxLogDebug(wxT("Event handler (RT_MainFrame::ResetCursorHandler) not implemented yet"));
}

void RT_MainFrame::SortEventNameHandler(wxCommandEvent &event)  // wxGlade: RT_MainFrame.<event_handler>
{
    event.Skip();
    // notify the user that he hasn't implemented the event handler yet
    wxLogDebug(wxT("Event handler (RT_MainFrame::SortEventNameHandler) not implemented yet"));
}

void RT_MainFrame::SortNumOccurHandler(wxCommandEvent &event)  // wxGlade: RT_MainFrame.<event_handler>
{
    event.Skip();
    // notify the user that he hasn't implemented the event handler yet
    wxLogDebug(wxT("Event handler (RT_MainFrame::SortNumOccurHandler) not implemented yet"));
}

void RT_MainFrame::SortAvgHandler(wxCommandEvent &event)  // wxGlade: RT_MainFrame.<event_handler>
{
    event.Skip();
    // notify the user that he hasn't implemented the event handler yet
    wxLogDebug(wxT("Event handler (RT_MainFrame::SortAvgHandler) not implemented yet"));
}

void RT_MainFrame::SortMaxDurationHandler(wxCommandEvent &event)  // wxGlade: RT_MainFrame.<event_handler>
{
    event.Skip();
    // notify the user that he hasn't implemented the event handler yet
    wxLogDebug(wxT("Event handler (RT_MainFrame::SortMaxDurationHandler) not implemented yet"));
}

void RT_MainFrame::SortMinDurationHandler(wxCommandEvent &event)  // wxGlade: RT_MainFrame.<event_handler>
{
    event.Skip();
    // notify the user that he hasn't implemented the event handler yet
    wxLogDebug(wxT("Event handler (RT_MainFrame::SortMinDurationHandler) not implemented yet"));
}

void RT_MainFrame::SortPctActHandler(wxCommandEvent &event)  // wxGlade: RT_MainFrame.<event_handler>
{
    event.Skip();
    // notify the user that he hasn't implemented the event handler yet
    wxLogDebug(wxT("Event handler (RT_MainFrame::SortPctActHandler) not implemented yet"));
}

void RT_MainFrame::ColorPickerHandler(wxCommandEvent &event)  // wxGlade: RT_MainFrame.<event_handler>
{
    event.Skip();
    // notify the user that he hasn't implemented the event handler yet
    wxLogDebug(wxT("Event handler (RT_MainFrame::ColorPickerHandler) not implemented yet"));
}

void RT_MainFrame::AboutHandler(wxCommandEvent &event)  // wxGlade: RT_MainFrame.<event_handler>
{
    event.Skip();
    // notify the user that he hasn't implemented the event handler yet
    wxLogDebug(wxT("Event handler (RT_MainFrame::AboutHandler) not implemented yet"));
}

void RT_MainFrame::handle_move_top(wxCommandEvent &event)  // wxGlade: RT_MainFrame.<event_handler>
{
    event.Skip();
    // notify the user that he hasn't implemented the event handler yet
    wxLogDebug(wxT("Event handler (RT_MainFrame::handle_move_top) not implemented yet"));
}

void RT_MainFrame::handle_move_up(wxCommandEvent &event)  // wxGlade: RT_MainFrame.<event_handler>
{
    event.Skip();
    // notify the user that he hasn't implemented the event handler yet
    wxLogDebug(wxT("Event handler (RT_MainFrame::handle_move_up) not implemented yet"));
}

void RT_MainFrame::handle_move_down(wxCommandEvent &event)  // wxGlade: RT_MainFrame.<event_handler>
{
    event.Skip();
    // notify the user that he hasn't implemented the event handler yet
    wxLogDebug(wxT("Event handler (RT_MainFrame::handle_move_down) not implemented yet"));
}

void RT_MainFrame::handle_move_bottom(wxCommandEvent &event)  // wxGlade: RT_MainFrame.<event_handler>
{
    event.Skip();
    // notify the user that he hasn't implemented the event handler yet
    wxLogDebug(wxT("Event handler (RT_MainFrame::handle_move_bottom) not implemented yet"));
}

void RT_MainFrame::handle_filter_events(wxCommandEvent &event)  // wxGlade: RT_MainFrame.<event_handler>
{
    event.Skip();
    // notify the user that he hasn't implemented the event handler yet
    wxLogDebug(wxT("Event handler (RT_MainFrame::handle_filter_events) not implemented yet"));
}

void RT_MainFrame::handle_enter_timeline(wxCommandEvent &event)  // wxGlade: RT_MainFrame.<event_handler>
{
    event.Skip();
    // notify the user that he hasn't implemented the event handler yet
    wxLogDebug(wxT("Event handler (RT_MainFrame::handle_enter_timeline) not implemented yet"));
}

void RT_MainFrame::Curs1Set(wxCommandEvent &event)  // wxGlade: RT_MainFrame.<event_handler>
{
    event.Skip();
    // notify the user that he hasn't implemented the event handler yet
    wxLogDebug(wxT("Event handler (RT_MainFrame::Curs1Set) not implemented yet"));
}

void RT_MainFrame::Curs1Down(wxSpinEvent &event)  // wxGlade: RT_MainFrame.<event_handler>
{
    event.Skip();
    // notify the user that he hasn't implemented the event handler yet
    wxLogDebug(wxT("Event handler (RT_MainFrame::Curs1Down) not implemented yet"));
}

void RT_MainFrame::Curs1Up(wxSpinEvent &event)  // wxGlade: RT_MainFrame.<event_handler>
{
    event.Skip();
    // notify the user that he hasn't implemented the event handler yet
    wxLogDebug(wxT("Event handler (RT_MainFrame::Curs1Up) not implemented yet"));
}

void RT_MainFrame::Curs2Set(wxCommandEvent &event)  // wxGlade: RT_MainFrame.<event_handler>
{
    event.Skip();
    // notify the user that he hasn't implemented the event handler yet
    wxLogDebug(wxT("Event handler (RT_MainFrame::Curs2Set) not implemented yet"));
}

void RT_MainFrame::Curs2Down(wxSpinEvent &event)  // wxGlade: RT_MainFrame.<event_handler>
{
    event.Skip();
    // notify the user that he hasn't implemented the event handler yet
    wxLogDebug(wxT("Event handler (RT_MainFrame::Curs2Down) not implemented yet"));
}

void RT_MainFrame::Curs2Up(wxSpinEvent &event)  // wxGlade: RT_MainFrame.<event_handler>
{
    event.Skip();
    // notify the user that he hasn't implemented the event handler yet
    wxLogDebug(wxT("Event handler (RT_MainFrame::Curs2Up) not implemented yet"));
}


// wxGlade: add RT_MainFrame event handlers

