// -*- C++ -*-
//
// generated by wxGlade 0.9.5 on Thu May  7 16:48:42 2020
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef RT_MAINFRAME_H
#define RT_MAINFRAME_H

#include <wx/wx.h>
#include <wx/image.h>

// begin wxGlade: ::dependencies
#include <wx/spinbutt.h>
#include <wx/statline.h>
#include <wx/treectrl.h>
#include "EventCanvas.h"
// end wxGlade

// begin wxGlade: ::extracode
#include <EventCanvasApp.h>
// end wxGlade


class RT_MainFrame: public wxFrame {
public:
    // begin wxGlade: RT_MainFrame::ids
    enum {
        FileOpen_id = wxID_HIGHEST + 1000,
        DataSetAnnotation_id = wxID_HIGHEST + 1001,
        EventSearch_id = wxID_HIGHEST + 1002,
        MenuRefresh_id = wxID_HIGHEST + 1003,
        EventData_id = wxID_HIGHEST + 1004,
        CursorMenu_id = wxID_HIGHEST + 1005,
        ResetCursor_id = wxID_HIGHEST + 1006,
        SortEventName_id = wxID_HIGHEST + 1007,
        SortNumOccur_id = wxID_HIGHEST + 1008,
        SortAvg_id = wxID_HIGHEST + 1009,
        SortMaxDuration_id = wxID_HIGHEST + 1010,
        SortMinDuration_id = wxID_HIGHEST + 1011,
        SortPctAct_id = wxID_HIGHEST + 1012,
        ColorPicker_id = wxID_HIGHEST + 1013,
        move_top_id = wxID_HIGHEST + 1014,
        move_bottom_id = wxID_HIGHEST + 1015,
        filter_events_id = wxID_HIGHEST + 1016,
        timeline_endpoint_update_id = wxID_HIGHEST + 1017,
        set_1_id = wxID_HIGHEST + 1018,
        spin_1_id = wxID_HIGHEST + 1019,
        set_2_id = wxID_HIGHEST + 1020,
        spin_2_id = wxID_HIGHEST + 1021,
    };
    // end wxGlade

    RT_MainFrame(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: RT_MainFrame::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: RT_MainFrame::attributes
    wxMenu* FileMenu;
    wxMenuItem* FileOpen;
    wxMenuItem* FileQuit;
    wxMenu* EditMenu;
    wxMenu* ViewMenu;
    wxMenuItem* ZoomIn;
    wxMenuItem* ZoomOut;
    wxMenuItem* EventDataSummary;
    wxMenuItem* CursorMenu;
    wxMenuItem* ResetCursors;
    wxMenu* ToolsMenu;
    wxMenu* HelpMenu;
    wxMenuItem* AboutMenu;
    wxMenuBar* frame_1_menubar;
    wxToolBar* frame_1_toolbar;
    wxTreeCtrl* g_EventList;
    EventCanvas* g_EventFrame;
    wxTextCtrl* g_StartTime;
    wxPanel* g_timeScale;
    wxTextCtrl* g_EndTime;
    wxStaticText* g_TotalEventCount;
    wxStaticLine* static_line_1;
    wxTextCtrl* g_EventInfo;
    wxTextCtrl* g_CommentText;
    wxStaticLine* static_line_2;
    wxStaticText* label_1;
    wxTextCtrl* g_Curs1Time;
    wxSpinButton* spin_button_1;
    wxStaticText* label_2;
    wxTextCtrl* g_Curs2Time;
    wxSpinButton* spin_button_2;
    wxStaticText* g_CursDtime;
    wxStaticLine* static_line_2_copy;
    wxScrolledWindow* panel_1;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    void FileOpenHandler(wxCommandEvent &event); // wxGlade: <event_handler>
    void SaveHandler(wxCommandEvent &event); // wxGlade: <event_handler>
    void SaveAsHandler(wxCommandEvent &event); // wxGlade: <event_handler>
    void QuitHandler(wxCommandEvent &event); // wxGlade: <event_handler>
    void EditDataSetAnnotationHandler(wxCommandEvent &event); // wxGlade: <event_handler>
    void ZoomInHandler(wxCommandEvent &event); // wxGlade: <event_handler>
    void ZoomOutHandler(wxCommandEvent &event); // wxGlade: <event_handler>
    void ZoomFillHandler(wxCommandEvent &event); // wxGlade: <event_handler>
    void RefreshHandler(wxCommandEvent &event); // wxGlade: <event_handler>
    void EventDataHandler(wxCommandEvent &event); // wxGlade: <event_handler>
    void CursorMenuHandler(wxCommandEvent &event); // wxGlade: <event_handler>
    void ResetCursorHandler(wxCommandEvent &event); // wxGlade: <event_handler>
    void SortEventNameHandler(wxCommandEvent &event); // wxGlade: <event_handler>
    void SortNumOccurHandler(wxCommandEvent &event); // wxGlade: <event_handler>
    void SortAvgHandler(wxCommandEvent &event); // wxGlade: <event_handler>
    void SortMaxDurationHandler(wxCommandEvent &event); // wxGlade: <event_handler>
    void SortMinDurationHandler(wxCommandEvent &event); // wxGlade: <event_handler>
    void SortPctActHandler(wxCommandEvent &event); // wxGlade: <event_handler>
    void ColorPickerHandler(wxCommandEvent &event); // wxGlade: <event_handler>
    void AboutHandler(wxCommandEvent &event); // wxGlade: <event_handler>
    void handle_move_top(wxCommandEvent &event); // wxGlade: <event_handler>
    void handle_move_up(wxCommandEvent &event); // wxGlade: <event_handler>
    void handle_move_down(wxCommandEvent &event); // wxGlade: <event_handler>
    void handle_move_bottom(wxCommandEvent &event); // wxGlade: <event_handler>
    void handle_filter_events(wxCommandEvent &event); // wxGlade: <event_handler>
    void handle_enter_timeline(wxCommandEvent &event); // wxGlade: <event_handler>
    void Curs1Set(wxCommandEvent &event); // wxGlade: <event_handler>
    void Curs1Down(wxSpinEvent &event); // wxGlade: <event_handler>
    void Curs1Up(wxSpinEvent &event); // wxGlade: <event_handler>
    void Curs2Set(wxCommandEvent &event); // wxGlade: <event_handler>
    void Curs2Down(wxSpinEvent &event); // wxGlade: <event_handler>
    void Curs2Up(wxSpinEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // RT_MAINFRAME_H
