// -*- C++ -*- generated by wxGlade 0.6.3 on Thu Sep 22 13:41:38 2011

#include <wx/wx.h>
#include <wx/image.h>

#ifndef TEXTEDITDIALOG_H
#define TEXTEDITDIALOG_H

// begin wxGlade: ::dependencies
#include <wx/statline.h>
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade


class TextEditDialog: public wxDialog {
public:
    // begin wxGlade: TextEditDialog::ids
    // end wxGlade

    TextEditDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: TextEditDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: TextEditDialog::attributes
    wxTextCtrl* TextField;
    wxButton* ok_button;
    wxStaticLine* static_line_3;
    wxButton* clear_button;
    wxStaticLine* static_line_4;
    wxButton* cancel_button;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void handle_clear(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // TEXTEDITDIALOG_H
